# Database Configuration
# spring.r2dbc.url=r2dbc:postgresql://postgres:${POSTGRES_DOCKER_PORT}/${POSTGRES_DATABASE}
# spring.r2dbc.username=${POSTGRES_USER}
# spring.r2dbc.password=${POSTGRES_ROOT_PASSWORD}

# R2DBC Initialization
spring.r2dbc.initialization-mode=always

# Enable the application's conditional DB initializer (schema.sql + data.sql)
app.db.init=false

# JWT Configuration
# jwt.secret=${JWT_SECRET}
# jwt.access-token.expiration=${JWT_ACCESS_EXPIRATION_MS}
# jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION_MS}

# Server Configuration
# server.port=${SPRING_DOCKER_PORT}

# OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method

# Logging
logging.level.com.example.auth=DEBUG
